### PR TITLE
Refactored ShareKit to be re-usable as a Xcode sub-project

### PR DESCRIPTION
**Pull request by PeyloW**
ShareKit in it's current state is great, but packaged as a sample application, not as a re-usable component.

When a client drag and drops the code for ShareKit into their project all connection and history with the original project is lost. It is hard to update for a new version, and even harder to push fixes and additions upstream.

I have refactored the project to be used as a Xcode sub-project, so the code can be plugged into an existing application without modifications or breaking connections to the original repo.

I have changed the setup for the project to have three Targets:
- ShareKit - Produces a static library for use in other applications.
- ShareKitResources - Produces a bundle to be copied into other applications.
- SampleApp - A sample target that uses the products from the other two targets.

I have introduces the concept of run-time configuration instead of modifying constants in header files. This means that clients can use ShareKit without modifying a single line of code. Eg. "as-is", withour requiring code to be forked or copied, making it easier to push non-breaking modifications upstream. These changes are in SHKConfig.h.

I have written a longer blog-post about Xcode sub-projects, and git sub-modules, describing the rationale for these changes here: http://blog.jayway.com/2011/05/16/the-state-of-ios-open-source-and-what-to-do-about-it/

### CODE REVIEW

**Comment by cglong** [comment]
Thank you so much for doing all this! Great blog post too! Until @ideashower completes this pull request, I'm basing my project on your fork.

**Comment by postmechanical** [comment]
Documentation on the value type for the SHKConfig*Color keys would be a plus.

**Comment by postmechanical** [comment]
Anyone had any luck using this fork in an Xcode 4 workspace?

**Comment by PeyloW** [comment]
@alandon: I have added documentation for the color config keys. Both I and Kasper Hansen have used it with Xcode 4. Please describe your error if it does not work.

**Comment by postmechanical** [comment]
I've been trying to to use the jayway ShareKit fork as part of a project now built using a Xcode 4 workspace. Everything compiles and links just fine. Getting the ShareKitResources.bundle into the app bundle was a problem. Adding it to the app project's copy bundle resources using drag-and-drop caused Xcode 4 to crash and it could not be added by clicking the + button at the bottom of the copy bundle resources pane because it does not appear in the list of items eligible to add. It seems to be working using a Copy Files build phase in the app project, but NSLocalizedStringFromTableInBundle does not return properly localized strings on device.

**Pull request closed without merging**
