### PR TITLE
Added video support

### PR DESCRIPTION
**Pull request by whalec**
Hey firstly cheers for ShareKit man, it's awesome. 

We're using it on the Movember app we're currently finishing up, and it's been great. 

We required video sharing support for Facebook and Twitter though. I've added the support for video to Facebook and Twitter, and thought I'd send you a pull request to see if you want it in the main stream?

I think it's a useful addition the images, links etc. In adding support for it, I've actually changed the twitter images from img.ly to yFrog, as yFrog supports a more transparent method for uploading both images and videos, also I needed to change 1 small line in the FBConnect library as it was never going to work with videos, since it didn't set mimeTypes and file extensions properly resulting in a Movie Format Not Supported Error.

Please let me know if you see any holes in the implementation, and I'd be happy to fix them up for you.

Thanks again
Cameron Barrie(@whalec)

### CODE REVIEW

**Comment by ideashower** [comment]
Awesome!  I'm hoping to have some time later this week or early next week to finally compile all of the pull requests from the last month.  I'll keep you posted.

**Comment by ideashower** [comment]
I'm working on getting everything wrapped up today and was going through this commit.  It looks like your Facebook consumer keys are in the SHKConfig, can you remove them before I pull?  Thanks.

**Comment by whalec** [comment]
Ahh bugger, right you are. Sorry about that man. I've removed them now. Let me know if you need anything more done.

**Comment by ForrestShi** [comment]
I am waiting for upload video to facebook,twitter,youtube, really hope that I can test them soon.

**Comment by alariccole** [comment]
Any progress on this? It's the one thing ShareKit is missing ;)

**Comment by whalec** [comment]
Yeah I've had the pull request there for a while now. Sorry you'll need to ask ideashower about when it'll make it into master. Otherwise you could clone or fork this repo and merge it with the current master.

**Comment by alariccole** [comment]
I realize FB is changing things around and this could be brittle. But if it works, it'd be much easier than going the Youtube>Facebook route.

**Pull request closed without merging**
